### ISSUE TITLE
Failed under OSX because of missing ssh-askpass support

### ISSUE THREAD

**Issue by bianjiang** [CodeEffect/RemoteEdit#3]
OSX doesn't have ssh-askpass, so it would fail... You'll need to have this to get ssh-askpass.
https://github.com/markcarver/mac-ssh-askpass
But I think you can wrap it within your plugin, so we don't have to install this to the /usr/libexec folder manually

**Comment by CodeEffect** [comment]
You shouldn't need ssh-askpass. Where I referenced it I was trying to disable it (it didn't work but I just ignored that for now). 

Could you advise where it's failing and possibly post some console debug please and I'll see if I can fix.

**Comment by CodeEffect** [comment]
Closing this one as invalid. SSH Askpass is not required.
