### ISSUE TITLE
Upon calling Fuzzy File

### ISSUE THREAD

**Issue by randy3k** [CodeEffect/RemoteEdit#4]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 524, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'fuzzy'
```

I am not sure why it happens.
On Mac and ST 3.

**Comment by CodeEffect** [comment]
Should be resolved by last commits. I'd left the menu, command and keymap files as "fuzzy" -> "last_server" when the script had been updated to expect "action" -> "fuzzy". 

Should be fixed so please let me know if you're still having issues.

**Comment by randy3k** [comment]
Thanks. Fixed now. I love your plugin.

One feature request: there is a setting `dont_edit_ext` for not editing particular files, could you also add `don't_show_ext` for not showing them at all.

**Comment by randy3k** [comment]
Also,
Should Fuzzy File be disable when `enable_cat` is `false`?
My console reports the following in this case.

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Randy/Library/Application Support/Sublime Text 3/Packages/User/RemoteEdit/Cats/Gauss.cat'
```

**Comment by CodeEffect** [comment]
I've sort of got the first request on the list but not as eloquently as that so will add it ta :)

The second one has a TODO around it in the code so will get around to it at some point.

Cheers!

**Comment by CodeEffect** [comment]
https://github.com/CodeEffect/RemoteEdit/commit/a80a0cba4e1a9973db2a98151284fb60dce1ee10

Don't list extension added. This was the only way I could think to contact you. Is there a better way with github that I'm missing, am somewhat of a GH n00b. If I've missed something or you had other requests please bung another bug up :)
